# Generated by Django 5.1.6 on 2025-07-20 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='emergency contact name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='emergency contact phone'),
        ),
    ]
